### ISSUE TITLE
RNAcentral results

### ISSUE THREAD

**Issue by hamzaaitabbou96** [RNAcentral/rnacentral-sequence-search#127]
Hi,
I have a question about RNAcentral results, for similar sequences I got a list of 959 results how can I select the most similar ones.
And what is the meaning of these variables : 
"identity": 87.5,
"query_coverage": 92.3076923076923,
"target_coverage": 0.4903964037597058,
"alignment_sequence": "GCAGAGAUGUACUACAAGAAGCGU",
"species_priority": "d",

**Comment by carlosribas** [comment]
Hi @hamzaaitabbou96,

Thank you for your interest in RNAcentral.

You can sort results in different ways when using the [sequence search on our site](https://rnacentral.org/sequence-search/), such as by e-value, identity, query coverage, and target coverage. By default, the results are sorted by e-value. We also prioritise displaying results from certain species first, for example Homo sapiens (9606) and Mus musculus (10090).

In brief, here’s what these terms mean:

- Identity: The percentage of identical matches between the query sequence and the target sequence over the aligned region.
- Query coverage: The percentage of the query sequence that is included in the alignment with the target sequence.
- Target coverage: The percentage of the target sequence that is included in the alignment with the query sequence.
- Alignment sequence: The specific portion of the query sequence that aligns with the target sequence, indicating the region of similarity between the two sequences.
- Species priority: Some species have higher priority in search results. You can see the logic used in [this part of the code](https://github.com/RNAcentral/rnacentral-sequence-search/blob/1ea7cbcc5bd078fa5c4ca221c89c1f92c0f90209/sequence_search/db/jobs.py#L412).

If you require any further information, feel free to contact me.

**Comment by hamzaaitabbou96** [comment]
can you explain me what is e-value, how to calculate it and how to select the most similar one with e-value.

**Comment by carlosribas** [comment]
e-value is a parameter that describes the number of hits one can expect to see by chance when searching a database of a particular size. 

Our sequence search is performed by the nhmmer and it is this software that calculates the e-value. [This page](https://rnacentral.org/help/sequence-search) explains how the search is performed.

**Comment by carlosribas** [comment]
I'm closing this issue, but feel free to create another one if you still have questions about our sequence search tool
