### ISSUE TITLE
Hide names of chunks being searched

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-sequence-search#43]
I fear that users will start wondering about what is in whitespace.fasta and so forth. Hide it and use something simple.

**Comment by BurkovBA** [comment]
I'm definitely not going to show those things on the production website (rnacentral.org, test.rnacentral.org etc.).

As for the standalone web interface of sequence search microservice, I'm not sure. Nobody's going to see it unless they really want to. And I'd really want to see those things as a developer.

**Comment by AntonPetrov** [comment]
I'd keep it for internal use too but to make it more helpful I would sort the chunks by status and then by name.

Perhaps in production the progress can be displayed as a progress bar?

**Comment by BurkovBA** [comment]
Yep, will display as progress bar in production. Done sorting by database name so that they don't jump around, added elapsedTime.
