### ISSUE TITLE
When zero results give option to search all data

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-sequence-search#44]
As I understand it right now we search a subset. If we do a search that gets 0 results, then we would probably want to show a link to redo search with on all sequences.

**Comment by AntonPetrov** [comment]
Yes, it's a subset of rRNAs + everything that's not an rRNA. Not sure if searching the whole rRNA set will ever be feasible

**Comment by blakesweeney** [comment]
If there is one thing the pipeline has taught me is that, more jobs will fix any performance problem.
