### ISSUE TITLE
Different results than in current search

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-sequence-search#46]
When I search for: 
```
GGCAGUUAUUAGGUUCAGUCCUGGAUCAAUCCUCGCUGAUGUAAAUGUAACAUUUACAACUGUACCCACUAAUGAGGACAUAAUCAGCACUAUCACCACUGCAAACCUUACUUUUCCUGUCACCGGAGCAGAGGGUAAGUUAAACGAGCAUCUUCAACAAUGCAGUAUCAUUUUAAAAAAUUUUGGAUGCUUUUGGUAUUUCUCCUGUGUUAUUAGACUAUACAUUAGCUGUUACAUGUGA
```

I get results in current search but none in the test site. Is this because of the subset searched?

- [ ] Should update the database files with the later version from:

ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/sequences/.internal/sequence-search

**Comment by BurkovBA** [comment]
That's likely, yes. Will take a look though.

**Comment by AntonPetrov** [comment]
The sequence files are in sync now and the results should be the same.
