### ISSUE TITLE
Pagination still returns duplicated pages sometimes

### ISSUE THREAD

**Issue by BurkovBA** [RNAcentral/rnacentral-sequence-search#70]
Search for:

CUAUACAAUCUACUGUCUUUC

You'll find multiple entries of `Anolis carolinensis let-7 microRNA precursor URS00006C9229_28377`

**Comment by carlosribas** [comment]
Not sure if this is a pagination problem. I created a script to look for duplicate entries and this error does not occur when we use a single file for all-except-rrna and a single file for whitelist-rrna.

I can see multiple entries when we split these files. @AntonPetrov can you tell me if what I am doing makes sense? I will be happy to chat about this if you want.

**Comment by AntonPetrov** [comment]
This does not happen anymore - closing.
