### ISSUE TITLE
Monitor errors and performance

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/rnacentral-sequence-search#82]
We need to be able to see how well the new search performs and react when the pipeline is slow or when there are errors. Here are some initial ideas:

- [x] Show the number of searches on the [dashboard](http://193.62.55.44:8002/dashboard) (all searches, searches today and this week)
- [x] Show average search time (all time, today, this week)
- [x] Regularly run a specific search or check search results using nagios, UptimeRobot, or a custom script
- [x] Figure out how to maintain the information between when the infrastructure is recreated and the postgres database is wiped
- [x] Log errors to a Slack channel

**Comment by AntonPetrov** [comment]
Just as an example, the old search had this dashboard: https://rnacentral.org/sequence-search/dashboard although the graph is not very useful

**Comment by AntonPetrov** [comment]
One could either add this information to the dashboard interface in this repo (for example, http://193.62.55.44:8002/dashboard) or create a new dashboard in the rnacentral-webcode repository. Let's discuss both options.

**Comment by carlosribas** [comment]
Done!
