### ISSUE TITLE
Do not search for a sequence already in DB

### ISSUE THREAD

**Issue by carlosribas** [RNAcentral/rnacentral-sequence-search#89]
In this case we should show the results of the DB or cache. However, the system needs to redo the search after a new release.

**Comment by blakesweeney** [comment]
If the hash we assign to each sequence export is stable you could use that to determine when to rerun a search or not.

**Comment by carlosribas** [comment]
Thanks for the tip. I was wondering use the hash to know when to download and update files on our nfs server. I have to figure out the best way to do this in our code.
